# Generated by Django 4.0.6 on 2022-10-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.CharField(max_length=15, unique=True)),
                ('celula', models.IntegerField(default=0)),
                ('qtd_solicitacao', models.IntegerField(blank=True, default=0)),
                ('observacao', models.TextField()),
            ],
            options={
                'db_table': 'tbl_operacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamado', models.CharField(max_length=7, unique=True)),
                ('data_incidentes', models.DateField()),
                ('solicitante', models.CharField(max_length=30)),
                ('operacao', models.CharField(max_length=15)),
                ('andar', models.IntegerField()),
                ('periferico', models.CharField(max_length=10)),
                ('motivo', models.CharField(max_length=15)),
                ('observacao', models.TextField()),
            ],
            options={
                'db_table': 'tbl_solicitacao',
                'managed': True,
            },
        ),
    ]
