# Generated by Django 4.0.6 on 2022-09-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroEquipamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbloperacao',
            name='celula',
            field=models.IntegerField(default=0, max_length=9999),
        ),
    ]
