# Generated by Django 4.0.6 on 2022-08-23 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroEquipamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={},
        ),
    ]
