# Generated by Django 4.0.6 on 2022-10-17 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroEquipamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblsolicitacao',
            name='operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Incidentes_ativos', to='cadastroEquipamento.tbloperacao'),
        ),
    ]
