# Generated by Django 4.0.6 on 2022-09-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroEquipamento', '0002_tbloperacao_celula'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbloperacao',
            name='observacao',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbloperacao',
            name='celula',
            field=models.IntegerField(default=0),
        ),
    ]
