# Generated by Django 4.0.6 on 2022-10-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroEquipamento', '0002_alter_tblsolicitacao_operacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblsolicitacao',
            name='site',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblsolicitacao',
            name='sla',
            field=models.BooleanField(default=False),
        ),
    ]
