# Generated by Django 4.0.6 on 2022-09-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroEquipamento', '0003_solicitacao_observacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.CharField(max_length=15, unique=True)),
                ('qtd_solicitacao', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_operacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamado', models.CharField(max_length=7)),
                ('data_incidentes', models.DateField()),
                ('solicitante', models.CharField(max_length=30)),
                ('andar', models.IntegerField()),
                ('periferico', models.CharField(max_length=10)),
                ('motivo', models.CharField(max_length=15)),
                ('observacao', models.TextField()),
            ],
            options={
                'db_table': 'tbl_solicitacao',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Solicitacao',
        ),
    ]
