# Generated by Django 4.0.6 on 2022-10-24 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroEquipamento', '0004_tblperiferico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblsolicitacao',
            name='andar',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tblsolicitacao',
            name='operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Incidentes_ativos', to='cadastroEquipamento.tbloperacao'),
        ),
        migrations.AlterField(
            model_name='tblsolicitacao',
            name='solicitante',
            field=models.CharField(max_length=50),
        ),
    ]
