# Generated by Django 4.0.6 on 2022-10-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroEquipamento', '0005_alter_tblsolicitacao_andar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblperiferico',
            name='qtd_periferico',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
