# Generated by Django 4.0.6 on 2022-10-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroEquipamento', '0006_tblperiferico_qtd_periferico'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblsolicitacao',
            name='pas',
            field=models.TextField(default='Santana', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tblsolicitacao',
            name='observacao',
            field=models.TextField(max_length=50),
        ),
    ]
