# Generated by Django 4.0.6 on 2022-11-07 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroEquipamento', '0008_alter_tblsolicitacao_data_incidentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblsolicitacao',
            name='operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='incidentes_ativos', to='cadastroEquipamento.tbloperacao'),
        ),
        migrations.AlterField(
            model_name='tblsolicitacao',
            name='periferico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='perifericos', to='cadastroEquipamento.tblperiferico'),
        ),
    ]
