# Generated by Django 4.0.6 on 2022-11-16 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroEquipamento', '0011_alter_tblsolicitacao_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblsolicitacao',
            name='operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_ativos', to='cadastroEquipamento.tbloperacao'),
        ),
    ]
