# Generated by Django 4.0.6 on 2022-12-03 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroEquipamento', '0012_alter_tblsolicitacao_operacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblsolicitacao',
            options={'managed': True, 'ordering': ['-data_incidentes']},
        ),
        migrations.AddField(
            model_name='tblperiferico',
            name='observacao',
            field=models.TextField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tblsolicitacao',
            name='observacao',
            field=models.TextField(max_length=70),
        ),
        migrations.AlterField(
            model_name='tblsolicitacao',
            name='periferico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perifericos', to='cadastroEquipamento.tblperiferico'),
        ),
    ]
