# Generated by Django 4.0.6 on 2022-12-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroEquipamento', '0013_alter_tblsolicitacao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblperiferico',
            name='observacao',
            field=models.TextField(blank=True, max_length=70, null=True),
        ),
    ]
